name: Release Madeezi Lucide Packages

on:
  push:
    tags:
      - 'v*'

  workflow_call:
    inputs:
      version:
        required: true
        description: Version
        type: string

  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  pre-release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Get the version
        id: get_version
        run: |
          echo $VERSION_REF
          echo "VERSION=${VERSION_REF/refs\/tags\/\v}" >> $GITHUB_OUTPUT
        env:
          VERSION_REF: ${{ inputs.version || github.event.inputs.version || github.ref }}

  release:
    runs-on: ubuntu-latest
    needs: pre-release
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: 'lucide-react'
            publish_name: '@madeezi/lucide'
          - package: 'lucide-react-native'
            publish_name: '@madeezi/lucide-react-native'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Auth Token for GitHub Packages
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm config set @madeezi:registry https://npm.pkg.github.com

      - name: Set new version
        run: pnpm --filter ${{ matrix.package }} version --new-version ${{ needs.pre-release.outputs.VERSION }} --no-git-tag-version

      - name: Build
        run: pnpm --filter ${{ matrix.package }} build

      - name: Test
        run: pnpm --filter ${{ matrix.package }} test

      - name: Update package name and registry for publishing
        run: |
          cd packages/${{ matrix.package }}
          npm pkg set name="${{ matrix.publish_name }}"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"

      - name: Publish to GitHub Packages
        run: |
          cd packages/${{ matrix.package }}
          npm publish --registry https://npm.pkg.github.com --access public


